# Generated by Django 5.2.4 on 2025-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemode',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
